galaxy_url: http://your/galaxy/url
galaxy_api_key: your_galaxy_api_key
galaxy_config: universe_wsgi.ini
program:
  bowtie: bowtie
  bwa: bwa
  tophat: tophat
  cufflinks: cufflinks
  ucsc_bigwig: wigToBigWig
  picard: /usr/share/java/picard
  gatk: /usr/share/java/gatk
  snpEff: /usr/share/java/snpeff
  fastqc: fastqc
  pdflatex: pdflatex
  barcode: barcode_sort_trim.py
algorithm:
  aligner: bowtie
  max_errors: 2
  num_cores: 8
  platform: illumina
  recalibrate: false
  snpcall: false
  bc_mismatch: 2
  bc_allow_indels: true
  bc_read: 1
  bc_position: 3
  java_memory: 6g
  upload_fastq: false
  save_diskspace: true

log_dir: log

analysis:
  # Can specify a different remote host to initiate
  # the copy from. This is useful for NFS shared filesystems
  # where you want to manage the copy from the base machine.
  copy_user:
  copy_host:
  store_dir: /store4/solexadata
  base_dir: /array0/projects/Sequencing
  towig_script: bam_to_wiggle.py
  process_program: automated_initial_analysis.py
  distributed_process_program: distributed_nextgen_pipeline.py
  upload_program: upload_to_galaxy.py
  worker_program: nextgen_analysis_server.py
distributed:
  cluster_platform: lsf
  platform_args: '-q your_queue_name'
  cores_per_host: 1 # 0 uses all cores, otherwise can configure for architecture
  # num_workers: 2 # only required if cores_per_host is 0, otherwise use all needed
  rabbitmq_vhost: bionextgen
# configuration algorithm changes for custom post-processing steps
custom_algorithms:
  'SNP calling':
    aligner: bwa
    recalibrate: true
    recalibration_plots: false
    snpcall: true
    coverage_depth: "high" # other options: low
    coverage_interval: "exome" # other options: genome, regional
    dbsnp: variation/dbsnp_132.vcf
    train_hapmap: variation/hapmap_3.3.vcf
    train_1000g_omni: variation/1000G_omni2.5.vcf
    train_indels: variation/Mills_Devine_2hit.indels.vcf
  'RNA-seq':
    aligner: tophat
    transcript_assemble: true
    transcripts: rnaseq/ref-transcripts.gtf
    transcripts_mask: rnaseq/ref-transcripts-mask.gtf
  'Minimal':
    aligner: ""
# Define resources to be used for individual programs on multicore machines.
# These can be defined specifically for memory and processor availability.
# Distributed systems 
# - Specify usage for memory intensive programs
# - Define cores that can be used for multicore programs.
resources:
  ucsc_bigwig:
    memory: 36g
  bowtie:
    cores:
  tophat:
    cores:
  bwa:
    cores:
  gatk:
    cores:
  cufflinks:
    cores:
  
