galaxy_url: http://your/galaxy/url
galaxy_api_key: your_galaxy_api_key
galaxy_config: universe_wsgi.ini
program:
  bowtie: bowtie
  samtools: samtools
  bwa: bwa
  ucsc_bigwig: wigToBigWig
  picard: /usr/share/java/picard
  gatk: /usr/share/java/gatk
  snpEff: /usr/share/java/snpeff
  fastqc: fastqc
  pdflatex: pdflatex
  barcode: barcode_sort_trim.py
algorithm:
  aligner: bowtie
  max_errors: 2
  num_cores: 8
  platform: illumina
  recalibrate: false
  snpcall: false
  bc_mismatch: 2
  bc_allow_indels: true
  bc_read: 1
  bc_position: 3
  java_memory: 6g
  upload_fastq: false
  save_diskspace: true

log_dir: log
msg_process_tag: sqn_finished_process
msg_store_tag: sqn_finished_store
store_dir: /mad/store/clients/cscshared/solexadata
store_user: cscshared
store_host: bricklayer01.partners.org

analysis:
  # Can specify a remote server to copy analysis files and run
  # the analysis programs on. This needs a configuration file 
  # like this with program information for the remote machine.
  # The default is to run the analysis on the local machine.
  # You can also specify a different remote host to initiate
  # the copy from. This is useful for NFS shared filesystems
  # where you want to manage the copy from the base machine.
  user:
  host:
  login_shell:
  config_file: /path/to/remote/post_process.yaml
  copy_user:
  copy_host:
  store_dir: /store4/solexadata
  base_dir: /array0/projects/Sequencing
  towig_script: bam_to_wiggle.py
  process_program: automated_initial_analysis.py
  upload_program: upload_to_galaxy.py
  worker_program: nextgen_analysis_server.py
distributed:
  cluster_platform: lsf
  platform_args: '-q long_parallel -n 4 -R "rusage=[1500m]"'
  num_workers: 2
  cores_per_host: 0 # zero uses all cores, otherwise can configure
  rabbitmq_vhost: bionextgen
# configuration algorithm changes for custom post-processing steps
custom_algorithms:
  'SNP calling':
    aligner: bwa
    recalibrate: true
    snpcall: true
    dbsnp: variation/dbsnp_132.vcf
    hybrid_bait:
    hybrid_target:
  'Minimal':
    aligner: ""
